/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import java.awt.Color;
import Connector.ConnectorClass;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Mahin
 */
public class Add_admin extends javax.swing.JFrame {

    /**
     * Creates new form Add_admin
     */
    public Add_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lname = new javax.swing.JLabel();
        ldept = new javax.swing.JLabel();
        lphone = new javax.swing.JLabel();
        laddress = new javax.swing.JLabel();
        lcabin = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        tName = new javax.swing.JTextField();
        tPhone = new javax.swing.JTextField();
        tDept = new javax.swing.JTextField();
        tAddress = new javax.swing.JTextField();
        lmcost = new javax.swing.JLabel();
        ltcost = new javax.swing.JLabel();
        tMCost = new javax.swing.JTextField();
        tTCost = new javax.swing.JTextField();
        bAdd = new javax.swing.JButton();
        lId = new javax.swing.JLabel();
        tId = new javax.swing.JTextField();
        cCabin = new javax.swing.JComboBox<>();
        clear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lname.setText("Name :");
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 47, -1, -1));

        ldept.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ldept.setText("Depertment :");
        getContentPane().add(ldept, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 119, -1, -1));

        lphone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lphone.setText("Phone No :");
        getContentPane().add(lphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, -1, -1));

        laddress.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        laddress.setText("Address :");
        getContentPane().add(laddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 157, -1, -1));

        lcabin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lcabin.setText("Cabin Type :");
        getContentPane().add(lcabin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 221, 70, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Select Catagory");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 92, -1));

        jComboBox1.setBackground(new java.awt.Color(0, 102, 204));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doctor", "Nurse", "Cabin", "Medicine", "Disease" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 7, 89, -1));
        getContentPane().add(tName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 44, 160, -1));
        getContentPane().add(tPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 75, 160, -1));
        getContentPane().add(tDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 116, 160, -1));
        getContentPane().add(tAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 154, 160, -1));

        lmcost.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lmcost.setText("Medicine Cost :");
        getContentPane().add(lmcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 262, 89, -1));

        ltcost.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ltcost.setText("Treatment Cost :");
        getContentPane().add(ltcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        tMCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMCostActionPerformed(evt);
            }
        });
        getContentPane().add(tMCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 162, -1));

        tTCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTCostActionPerformed(evt);
            }
        });
        getContentPane().add(tTCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 162, -1));

        bAdd.setBackground(new java.awt.Color(153, 153, 153));
        bAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bAdd.setForeground(new java.awt.Color(51, 153, 0));
        bAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/add.png"))); // NOI18N
        bAdd.setText("ADD");
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddActionPerformed(evt);
            }
        });
        getContentPane().add(bAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 401, 91, 36));

        lId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lId.setText("Cabin No :");
        getContentPane().add(lId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 186, 61, 21));
        getContentPane().add(tId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 186, 160, -1));

        cCabin.setBackground(new java.awt.Color(0, 102, 204));
        cCabin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cCabin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ward", "ICU", "CCU", "HDU" }));
        cCabin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(cCabin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 160, -1));

        clear.setBackground(new java.awt.Color(153, 153, 153));
        clear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clear.setForeground(new java.awt.Color(0, 102, 204));
        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Reset.png"))); // NOI18N
        clear.setText("Reset");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 401, -1, 36));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/close Jframe.png"))); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 401, 85, 36));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/pill-tablet-pharmacy-medicine.jpg"))); // NOI18N
        jLabel1.setText("=");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        int selected =  jComboBox1.getSelectedIndex();
        if(selected==0)
        {
            lname.setForeground(Color.red);
            ldept.setForeground(Color.red);
            lphone.setForeground(Color.red);
            laddress.setForeground(Color.red);
           
            lcabin.setForeground(Color.black);
            lmcost.setForeground(Color.black);
            ltcost.setForeground(Color.black);
            lId.setForeground(Color.black);
        }
        if(selected==1)
        {
            lname.setForeground(Color.red);
            lphone.setForeground(Color.red);
            ldept.setForeground(Color.black);
             laddress.setForeground(Color.black);
           
            lcabin.setForeground(Color.black);
            lmcost.setForeground(Color.black);
            ltcost.setForeground(Color.black);
            lId.setForeground(Color.black);
            
        }
        if(selected==2)
        {   
             lname.setForeground(Color.black);
            lphone.setForeground(Color.black);
            ldept.setForeground(Color.black);
             laddress.setForeground(Color.black);
           
            lcabin.setForeground(Color.red);
            lmcost.setForeground(Color.black);
            ltcost.setForeground(Color.black);
            lId.setForeground(Color.red);
        }
         if(selected==3)
        {
            lname.setForeground(Color.red);
             lphone.setForeground(Color.black);
            ldept.setForeground(Color.black);
             laddress.setForeground(Color.black);
            
            lcabin.setForeground(Color.black);
            lmcost.setForeground(Color.red);
            ltcost.setForeground(Color.black);
            lId.setForeground(Color.black);
        }
          if(selected==4)
        {
            lname.setForeground(Color.red);
             lphone.setForeground(Color.black);
            ldept.setForeground(Color.black);
             laddress.setForeground(Color.black);
           
            lcabin.setForeground(Color.black);
            lmcost.setForeground(Color.black);
            ltcost.setForeground(Color.red);
            lId.setForeground(Color.black);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void bAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddActionPerformed
         int selected =  jComboBox1.getSelectedIndex();
         String name = tName.getText();
         String phone = tPhone.getText();
         String dept = tDept.getText();
         String address = tAddress.getText();
        
         String cabinno = tId.getText();
        
         String cabinType = cCabin.getSelectedItem().toString();
         String medicinecost = tMCost.getText();
         
         String treatmentcost = tTCost.getText();
       
                 
        try{
           Connection connection= ConnectorClass.getcon();
             if(selected==0)
             {
              
               String sqlInsert = "insert into Doctor values('"+name+"','"+dept+"','"+phone+"','"+address+"')";
               Statement statementToShow = connection.createStatement();
               int row = statementToShow.executeUpdate(sqlInsert);
               JOptionPane.showMessageDialog(null,"Added");
             }
             if(selected==1)
             {
              
               String sqlInsert = "insert into Nurse values('"+name+"','"+phone+"')";
               Statement statementToShow = connection.createStatement();
               int row = statementToShow.executeUpdate(sqlInsert);
               JOptionPane.showMessageDialog(null,"Added");
             }
             if(selected==2)
             {  
    
               String sqlInsert2 = "insert into Cabin values('"+cabinno+"','"+cabinType+"')";
               Statement statementToShow2 = connection.createStatement();
               int row = statementToShow2.executeUpdate(sqlInsert2);
               JOptionPane.showMessageDialog(null,"Added");
             }
             if(selected==3)
             {
              
               String sqlInsert = "insert into Medicine values('"+name+"','"+medicinecost+"')";
               Statement statementToShow = connection.createStatement();
               int row = statementToShow.executeUpdate(sqlInsert);
               JOptionPane.showMessageDialog(null,"Added");
             }
             if(selected==4)
             {
              
               String sqlInsert = "insert into Disease values('"+name+"','"+treatmentcost+"')";
               Statement statementToShow = connection.createStatement();
               int row = statementToShow.executeUpdate(sqlInsert);
               JOptionPane.showMessageDialog(null,"Added");
             }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
       
    }//GEN-LAST:event_bAddActionPerformed

    private void tTCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTCostActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        tName.setText("");
         tPhone.setText("");
         tDept.setText("");
         tAddress.setText("");
          
          tId.setText("");
        
         
         tMCost.setText("");
         
         tTCost.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Homepage_admin obj = new Homepage_admin();
        setVisible(false);
        obj.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tMCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tMCostActionPerformed
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdd;
    private javax.swing.JComboBox<String> cCabin;
    private javax.swing.JButton clear;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lId;
    private javax.swing.JLabel laddress;
    private javax.swing.JLabel lcabin;
    private javax.swing.JLabel ldept;
    private javax.swing.JLabel lmcost;
    private javax.swing.JLabel lname;
    private javax.swing.JLabel lphone;
    private javax.swing.JLabel ltcost;
    private javax.swing.JTextField tAddress;
    private javax.swing.JTextField tDept;
    private javax.swing.JTextField tId;
    private javax.swing.JTextField tMCost;
    private javax.swing.JTextField tName;
    private javax.swing.JTextField tPhone;
    private javax.swing.JTextField tTCost;
    // End of variables declaration//GEN-END:variables
}
