/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Connector.ConnectorClass;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mahin
 */
public class Nurse_admin extends javax.swing.JFrame {

    /**
     * Creates new form Nurse_admin
     */
    public Nurse_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Nurse");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setAlignmentX(3.0F);
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Select One :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 49, 93, 36));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Operator :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 91, 70, 31));

        jComboBox1.setBackground(new java.awt.Color(204, 0, 0));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Show all data", "search by id", "name", "phone" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 57, 154, -1));

        jComboBox2.setBackground(new java.awt.Color(255, 0, 0));
        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "like", "not like", "greater than", "less than" }));
        jComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 96, 154, -1));

        clear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clear.setForeground(new java.awt.Color(0, 51, 153));
        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Reset.png"))); // NOI18N
        clear.setText("Reset");
        clear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 512, 90, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "name", "phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(120);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(120);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 515, 254));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 96, 210, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 204));
        jButton1.setText("Enter");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 81, 36));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/delete.png"))); // NOI18N
        jButton2.setText("Delete");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 512, 82, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 153, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/rsz_1rsz_1rsz_1rsz_2rsz_1rsz_1rsz_1images_6.jpg"))); // NOI18N
        jButton3.setText("Update");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 509, 87, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Ascending sort :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 154, -1, -1));

        jComboBox3.setBackground(new java.awt.Color(255, 51, 0));
        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "id", "name", "phone" }));
        jComboBox3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 151, 118, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Descending sort :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 154, -1, -1));

        jComboBox4.setBackground(new java.awt.Color(255, 51, 0));
        jComboBox4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "id", "name", "phone" }));
        jComboBox4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBox4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 151, 115, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/close Jframe.png"))); // NOI18N
        jButton4.setText("Exit");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 512, 90, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/photo-1587370560942-ad2a04eabb6d.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_clearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.setRowCount(0);
        int selected =  jComboBox1.getSelectedIndex();
       int sel = jComboBox2.getSelectedIndex();
       String text = jTextField1.getText();
       
       try{
            Connection connection= ConnectorClass.getcon();
           //all
           if(selected==0)
           {
               String sqlShow = "select *from Nurse";
               Statement statementToShow = connection.createStatement();
               ResultSet result = statementToShow.executeQuery(sqlShow);
               while(result.next())
               {    
                   int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                   
                   model.addRow(new Object[]{ID, Name,Phone});
               }
               
           }
            //id
           if(selected==1)
           {
               if(sel==0)
               {
                  String sqlShow = "select *from Nurse where nurse_id = '"+text+"'";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==1)
               {
                  String sqlShow = "select *from Nurse where nurse_id like '%"+text+"%'";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                      int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==2)
               {
                  String sqlShow = "select *from Nurse where nurse_id not like '%"+text+"%'";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                   
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==3)
               {
                  String sqlShow = "select *from Nurse where nurse_id > '"+text+"'";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                      int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==4)
               {
                  String sqlShow = "select *from Nurse where nurse_id < '"+text+"'";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                 
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
           }
           //name
            if(selected==2)
           {
               if(sel==0)
               {
                  String sqlShow = "select *from Nurse where nurse_name = '"+text+"'";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                      int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==1)
               {
                  String sqlShow = "select *from Nurse where nurse_name like '%"+text+"%'";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==2)
               {
                  String sqlShow = "select *from Nurse where nurse_name not like '%"+text+"%'";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                      int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                   
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
           }
            //phone
           if(selected==3)
           {
               if(sel==0)
               {
                  String sqlShow = "select *from Nurse where nurse_phone = '"+text+"'";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                   
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==1)
               {
                  String sqlShow = "select *from Nurse where nurse_phone like '%"+text+"%'";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                 
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==2)
               {
                  String sqlShow = "select *from Nurse where nurse_phone not like '%"+text+"%'";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                    int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                 
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
           }
       }catch(Exception e)
       {
           
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int row = jTable1.getSelectedRow();
        String value = jTable1.getModel().getValueAt(row, 0).toString();
        String del = "delete from Nurse where nurse_id = '"+value+"'";
        try{
            Connection connection= ConnectorClass.getcon();
            Statement statementToShow = connection.createStatement();
            statementToShow.executeUpdate(del);
            JOptionPane.showMessageDialog(null,"Deleted");
        }catch(Exception e)
        {

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int row = jTable1.getSelectedRow();
        String value1 = jTable1.getModel().getValueAt(row, 0).toString();
        String value2 = jTable1.getModel().getValueAt(row, 1).toString();
        String value3 = jTable1.getModel().getValueAt(row, 2).toString();
      

        String update = "update Nurse set nurse_name='"+value2+"',nurse_phone='"+value3+"' where nurse_id = '"+value1+"'";
        try{
            Connection connection= ConnectorClass.getcon();
            Statement statementToShow = connection.createStatement();
            statementToShow.executeUpdate(update);
         
            JOptionPane.showMessageDialog(null,"Updated");

        }catch(Exception e)
        {

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int selected =  jComboBox1.getSelectedIndex();
       int sel = jComboBox2.getSelectedIndex();
       int sel2 = jComboBox3.getSelectedIndex();
       String text = jTextField1.getText();
       if(sel2!=0)
       {
           
           model.setRowCount(0);
       }
       
       try{
           Connection connection= ConnectorClass.getcon();
           
//1    
       if(sel2==1)
       {
           //all
           if(selected==0)
           {
               String sqlShow = "select *from Nurse order by nurse_id";
               Statement statementToShow = connection.createStatement();
               ResultSet result = statementToShow.executeQuery(sqlShow);
               while(result.next())
               {    
                   int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                   
                   model.addRow(new Object[]{ID, Name,Phone});
               }
               
           }
            //id
           if(selected==1)
           {
               if(sel==0)
               {
                  String sqlShow = "select *from Nurse where nurse_id = '"+text+"' order by nurse_id";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==1)
               {
                  String sqlShow = "select *from Nurse where nurse_id like '%"+text+"%' order by nurse_id";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                      int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==2)
               {
                  String sqlShow = "select *from Nurse where nurse_id not like '%"+text+"%' order by nurse_id";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                   
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==3)
               {
                  String sqlShow = "select *from Nurse where nurse_id > '"+text+"' order by nurse_id";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                      int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==4)
               {
                  String sqlShow = "select *from Nurse where nurse_id < '"+text+"' order by nurse_id";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                 
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
           }
           //name
            if(selected==2)
           {
               if(sel==0)
               {
                  String sqlShow = "select *from Nurse where nurse_name = '"+text+"' order by nurse_id";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                      int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==1)
               {
                  String sqlShow = "select *from Nurse where nurse_name like '%"+text+"%' order by nurse_id";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==2)
               {
                  String sqlShow = "select *from Nurse where nurse_name not like '%"+text+"%' order by nurse_id";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                      int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                   
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
           }
            //phone
           if(selected==3)
           {
               if(sel==0)
               {
                  String sqlShow = "select *from Nurse where nurse_phone = '"+text+"' order by nurse_id";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                   
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==1)
               {
                  String sqlShow = "select *from Nurse where nurse_phone like '%"+text+"%' order by nurse_id";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                 
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==2)
               {
                  String sqlShow = "select *from Nurse where nurse_phone not like '%"+text+"%' order by nurse_id";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                    int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                 
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
           }
       }
//2   
       if(sel2==2)
       {
           //all
           if(selected==0)
           {
               String sqlShow = "select *from Nurse order by nurse_name";
               Statement statementToShow = connection.createStatement();
               ResultSet result = statementToShow.executeQuery(sqlShow);
               while(result.next())
               {    
                   int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                   
                   model.addRow(new Object[]{ID, Name,Phone});
               }
               
           }
            //id
           if(selected==1)
           {
               if(sel==0)
               {
                  String sqlShow = "select *from Nurse where nurse_id = '"+text+"' order by nurse_name";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==1)
               {
                  String sqlShow = "select *from Nurse where nurse_id like '%"+text+"%' order by nurse_name";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                      int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==2)
               {
                  String sqlShow = "select *from Nurse where nurse_id not like '%"+text+"%' order by nurse_name";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                   
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==3)
               {
                  String sqlShow = "select *from Nurse where nurse_id > '"+text+"' order by nurse_name";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                      int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==4)
               {
                  String sqlShow = "select *from Nurse where nurse_id < '"+text+"' order by nurse_name";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                 
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
           }
           //name
            if(selected==2)
           {
               if(sel==0)
               {
                  String sqlShow = "select *from Nurse where nurse_name = '"+text+"' order by nurse_name";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                      int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==1)
               {
                  String sqlShow = "select *from Nurse where nurse_name like '%"+text+"%' order by nurse_name";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==2)
               {
                  String sqlShow = "select *from Nurse where nurse_name not like '%"+text+"%' order by nurse_name";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                      int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                   
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
           }
            //phone
           if(selected==3)
           {
               if(sel==0)
               {
                  String sqlShow = "select *from Nurse where nurse_phone = '"+text+"' order by nurse_name";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                   
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==1)
               {
                  String sqlShow = "select *from Nurse where nurse_phone like '%"+text+"%' order by nurse_name";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                 
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==2)
               {
                  String sqlShow = "select *from Nurse where nurse_phone not like '%"+text+"%' order by nurse_name";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                    int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                 
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
           }
       }
//3   
       if(sel2==3)
       {
           //all
           if(selected==0)
           {
               String sqlShow = "select *from Nurse order by nurse_phone";
               Statement statementToShow = connection.createStatement();
               ResultSet result = statementToShow.executeQuery(sqlShow);
               while(result.next())
               {    
                   int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                   
                   model.addRow(new Object[]{ID, Name,Phone});
               }
               
           }
            //id
           if(selected==1)
           {
               if(sel==0)
               {
                  String sqlShow = "select *from Nurse where nurse_id = '"+text+"' order by nurse_phone";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==1)
               {
                  String sqlShow = "select *from Nurse where nurse_id like '%"+text+"%' order by nurse_phone";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                      int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==2)
               {
                  String sqlShow = "select *from Nurse where nurse_id not like '%"+text+"%' order by nurse_phone";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                   
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==3)
               {
                  String sqlShow = "select *from Nurse where nurse_id > '"+text+"' order by nurse_phone";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                      int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==4)
               {
                  String sqlShow = "select *from Nurse where nurse_id < '"+text+"' order by nurse_phone";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                 
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
           }
           //name
            if(selected==2)
           {
               if(sel==0)
               {
                  String sqlShow = "select *from Nurse where nurse_name = '"+text+"' order by nurse_phone";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                      int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==1)
               {
                  String sqlShow = "select *from Nurse where nurse_name like '%"+text+"%' order by nurse_phone";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==2)
               {
                  String sqlShow = "select *from Nurse where nurse_name not like '%"+text+"%' order by nurse_phone";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                      int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                   
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
           }
            //phone
           if(selected==3)
           {
               if(sel==0)
               {
                  String sqlShow = "select *from Nurse where nurse_phone = '"+text+"' order by nurse_phone";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                   
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==1)
               {
                  String sqlShow = "select *from Nurse where nurse_phone like '%"+text+"%' order by nurse_phone";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                 
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==2)
               {
                  String sqlShow = "select *from Nurse where nurse_phone not like '%"+text+"%' order by nurse_phone";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                    int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                 
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
           }
       }
           
       }catch(Exception e)
       {
           
       }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int selected =  jComboBox1.getSelectedIndex();
       int sel = jComboBox2.getSelectedIndex();
       int sel2 = jComboBox4.getSelectedIndex();
       String text = jTextField1.getText();
       if(sel2!=0)
       {
           
           model.setRowCount(0);
       }
       
       try{
           Connection connection= ConnectorClass.getcon();
           
//1    
       if(sel2==1)
       {
           //all
           if(selected==0)
           {
               String sqlShow = "select *from Nurse order by nurse_id desc";
               Statement statementToShow = connection.createStatement();
               ResultSet result = statementToShow.executeQuery(sqlShow);
               while(result.next())
               {    
                   int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                   
                   model.addRow(new Object[]{ID, Name,Phone});
               }
               
           }
            //id
           if(selected==1)
           {
               if(sel==0)
               {
                  String sqlShow = "select *from Nurse where nurse_id = '"+text+"' order by nurse_id desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==1)
               {
                  String sqlShow = "select *from Nurse where nurse_id like '%"+text+"%' order by nurse_id desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                      int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==2)
               {
                  String sqlShow = "select *from Nurse where nurse_id not like '%"+text+"%' order by nurse_id desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                   
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==3)
               {
                  String sqlShow = "select *from Nurse where nurse_id > '"+text+"' order by nurse_id desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                      int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==4)
               {
                  String sqlShow = "select *from Nurse where nurse_id < '"+text+"' order by nurse_id desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                 
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
           }
           //name
            if(selected==2)
           {
               if(sel==0)
               {
                  String sqlShow = "select *from Nurse where nurse_name = '"+text+"' order by nurse_id desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                      int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==1)
               {
                  String sqlShow = "select *from Nurse where nurse_name like '%"+text+"%' order by nurse_id desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==2)
               {
                  String sqlShow = "select *from Nurse where nurse_name not like '%"+text+"%' order by nurse_id desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                      int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                   
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
           }
            //phone
           if(selected==3)
           {
               if(sel==0)
               {
                  String sqlShow = "select *from Nurse where nurse_phone = '"+text+"' order by nurse_id desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                   
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==1)
               {
                  String sqlShow = "select *from Nurse where nurse_phone like '%"+text+"%' order by nurse_id desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                 
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==2)
               {
                  String sqlShow = "select *from Nurse where nurse_phone not like '%"+text+"%' order by nurse_id desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                    int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                 
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
           }
       }
//2   
       if(sel2==2)
       {
           //all
           if(selected==0)
           {
               String sqlShow = "select *from Nurse order by nurse_name desc";
               Statement statementToShow = connection.createStatement();
               ResultSet result = statementToShow.executeQuery(sqlShow);
               while(result.next())
               {    
                   int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                   
                   model.addRow(new Object[]{ID, Name,Phone});
               }
               
           }
            //id
           if(selected==1)
           {
               if(sel==0)
               {
                  String sqlShow = "select *from Nurse where nurse_id = '"+text+"' order by nurse_name desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==1)
               {
                  String sqlShow = "select *from Nurse where nurse_id like '%"+text+"%' order by nurse_name desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                      int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==2)
               {
                  String sqlShow = "select *from Nurse where nurse_id not like '%"+text+"%' order by nurse_name desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                   
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==3)
               {
                  String sqlShow = "select *from Nurse where nurse_id > '"+text+"' order by nurse_name desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                      int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==4)
               {
                  String sqlShow = "select *from Nurse where nurse_id < '"+text+"' order by nurse_name desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                 
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
           }
           //name
            if(selected==2)
           {
               if(sel==0)
               {
                  String sqlShow = "select *from Nurse where nurse_name = '"+text+"' order by nurse_name desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                      int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==1)
               {
                  String sqlShow = "select *from Nurse where nurse_name like '%"+text+"%' order by nurse_name desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==2)
               {
                  String sqlShow = "select *from Nurse where nurse_name not like '%"+text+"%' order by nurse_name desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                      int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                   
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
           }
            //phone
           if(selected==3)
           {
               if(sel==0)
               {
                  String sqlShow = "select *from Nurse where nurse_phone = '"+text+"' order by nurse_name desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                   
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==1)
               {
                  String sqlShow = "select *from Nurse where nurse_phone like '%"+text+"%' order by nurse_name desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                 
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==2)
               {
                  String sqlShow = "select *from Nurse where nurse_phone not like '%"+text+"%' order by nurse_name desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                    int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                 
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
           }
       }
//3   
       if(sel2==3)
       {
           //all
           if(selected==0)
           {
               String sqlShow = "select *from Nurse order by nurse_phone desc";
               Statement statementToShow = connection.createStatement();
               ResultSet result = statementToShow.executeQuery(sqlShow);
               while(result.next())
               {    
                   int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                   
                   model.addRow(new Object[]{ID, Name,Phone});
               }
               
           }
            //id
           if(selected==1)
           {
               if(sel==0)
               {
                  String sqlShow = "select *from Nurse where nurse_id = '"+text+"' order by nurse_phone desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==1)
               {
                  String sqlShow = "select *from Nurse where nurse_id like '%"+text+"%' order by nurse_phone desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                      int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==2)
               {
                  String sqlShow = "select *from Nurse where nurse_id not like '%"+text+"%' order by nurse_phone desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                   
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==3)
               {
                  String sqlShow = "select *from Nurse where nurse_id > '"+text+"' order by nurse_phone desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                      int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==4)
               {
                  String sqlShow = "select *from Nurse where nurse_id < '"+text+"' order by nurse_phone desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                 
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
           }
           //name
            if(selected==2)
           {
               if(sel==0)
               {
                  String sqlShow = "select *from Nurse where nurse_name = '"+text+"' order by nurse_phone desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                      int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==1)
               {
                  String sqlShow = "select *from Nurse where nurse_name like '%"+text+"%' order by nurse_phone desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                  
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==2)
               {
                  String sqlShow = "select *from Nurse where nurse_name not like '%"+text+"%' order by nurse_phone desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                      int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                   
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
           }
            //phone
           if(selected==3)
           {
               if(sel==0)
               {
                  String sqlShow = "select *from Nurse where nurse_phone = '"+text+"' order by nurse_phone desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                   
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==1)
               {
                  String sqlShow = "select *from Nurse where nurse_phone like '%"+text+"%' order by nurse_phone desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                     int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                 
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
               if(sel==2)
               {
                  String sqlShow = "select *from Nurse where nurse_phone not like '%"+text+"%' order by nurse_phone desc";
                  Statement statementToShow = connection.createStatement();
                  ResultSet result = statementToShow.executeQuery(sqlShow);
                  while(result.next())
                  {    
                    int ID = result.getInt("nurse_id");
                   String Name = result.getString("nurse_name");
                   
                   String Phone = result.getString("nurse_phone");
                   
                  
                 
                   model.addRow(new Object[]{ID, Name,Phone});
                  }
               }
           }
       }
           
       }catch(Exception e)
       {
           
       }
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        View_admin obj = new View_admin();
        setVisible(false);
        obj.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nurse_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nurse_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nurse_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nurse_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nurse_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
