/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Recep;
import java.awt.Color;
import Connector.ConnectorClass;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Mahin
 */
public class Payment_recep extends javax.swing.JFrame {

    /**
     * Creates new form Payment_recep
     */
    public Payment_recep() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        p_ID = new javax.swing.JLabel();
        p_id = new javax.swing.JTextField();
        Mname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Quantity = new javax.swing.JTextField();
        MedicineCost = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tCost = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        Totalc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        t = new javax.swing.JLabel();
        Mcosts = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Medicine Name :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 34, -1, -1));

        p_ID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        p_ID.setText("Patient Id:");
        getContentPane().add(p_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, -1));

        p_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_idActionPerformed(evt);
            }
        });
        getContentPane().add(p_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 186, -1));

        Mname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnameActionPerformed(evt);
            }
        });
        getContentPane().add(Mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 31, 187, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Quantity :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 64, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Medicine Rate:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, -1, -1));
        getContentPane().add(Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 64, 187, -1));

        MedicineCost.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(MedicineCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 94, 187, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Treatment Cost:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 284, -1, -1));

        tCost.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(tCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 120, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 142, 720, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Total Cost :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 314, -1, 37));

        Totalc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Totalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalcActionPerformed(evt);
            }
        });
        getContentPane().add(Totalc, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 324, 120, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recep/add.png"))); // NOI18N
        jButton1.setText("Add Medicine ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 74, 140, 36));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Id", "Medicine Name", "Rate", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 187, 464, 240));

        t.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t.setText("Medicine Cost :");
        getContentPane().add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 236, -1, -1));

        Mcosts.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Mcosts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                McostsActionPerformed(evt);
            }
        });
        getContentPane().add(Mcosts, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 120, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Calculation Details:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 181, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 205, 240, 10));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recep/add.png"))); // NOI18N
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 363, 85, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recep/close Jframe.png"))); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 363, 80, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recep/photo-1587370560942-ad2a04eabb6d.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_idActionPerformed

        String pId=p_id.getText();

        try{

            Connection connection=ConnectorClass.getcon();
            String dId="select *from Patient where patient_id = '"+pId+"'"  ;
            Statement statement = connection.createStatement();
            ResultSet rs=statement.executeQuery(dId);
            while(rs.next())
            {
                int id= rs.getInt("patient_disease_id");
                String tId="select *from Disease where disease_id = '"+id+"'";
                Statement statement2 = connection.createStatement();
                ResultSet rs2=statement2.executeQuery(tId);
                while(rs2.next())
                {
                    int id2= rs2.getInt("disease_treatment_cost");
                    String cost = Integer.toString(id2);
                    tCost.setText(cost);
                }

            }

            Mcosts.setEditable(false);
            tCost.setEditable(false);
            Totalc.setEditable(false);

        }catch(Exception e)
        {
          
        }
    }//GEN-LAST:event_p_idActionPerformed

    private void MnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnameActionPerformed
        String name=Mname.getText();
        try{
            String cost="select * from Medicine where medicine_name='"+name+"'" ;
            Connection connection=ConnectorClass.getcon();
            Statement statementToShow = connection.createStatement();
            ResultSet rs=statementToShow.executeQuery(cost);

            if(rs.next())
            {

                MedicineCost.setText(rs.getString(3));

            }
            else
            {
                JOptionPane.showMessageDialog(this,"Error! Enter right medicine name");
                MedicineCost.setText("");
            }

        }catch(Exception e)
        {

        }
    }//GEN-LAST:event_MnameActionPerformed

    private void TotalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalcActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int sum=0;
        int price=Integer.parseInt(MedicineCost.getText());
        int quantity=Integer.parseInt(Quantity.getText());
        int tPrice=Integer.parseInt(tCost.getText());
        int total= (price*quantity);
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[]{p_id.getText(),Mname.getText(),price,quantity,total});
        for(int i=0; i<jTable1.getRowCount();i++)
        {
            sum=sum+Integer.parseInt(jTable1.getValueAt(i,4).toString());
        }
        Mcosts.setText(String.valueOf(sum));
        int totalAmout=sum+tPrice;
        String TotalAmount =String.valueOf(totalAmout) ;
        Totalc.setText(TotalAmount);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void McostsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_McostsActionPerformed

    }//GEN-LAST:event_McostsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        new Payment_recep().setVisible(true);
        
        String id = p_id.getText();
        String medCost=Mcosts.getText();
        String trtCost=tCost.getText();
        String totalCost= Totalc.getText();
        
        try{
            Connection connection= ConnectorClass.getcon();
            
            String sqlShow = "select *from Bill where bill_patient_id='"+id+"'";
            Statement statementToShow = connection.createStatement();
            ResultSet result =  statementToShow.executeQuery(sqlShow);
            if(result.next())
            {
                 
                 int mCost = result.getInt("bill_medicine_cost");
                 int MedCost = Integer.parseInt(medCost);
                 int newMedCost = MedCost+mCost;
                 String updatedMedicineCost = Integer.toString(newMedCost);
                 
                 int toCost = result.getInt("bill_total_cost");
                 int TotalCost = MedCost + toCost;
                 String updatedTotalCost = Integer.toString(TotalCost);
                 
                 String update = "update Bill set bill_medicine_cost = '"+updatedMedicineCost+"',bill_total_cost = '"+updatedTotalCost+"' where bill_patient_id='"+id+"'";
                 Statement statementToShow1 = connection.createStatement();
                 statementToShow1.executeUpdate(update);
                 JOptionPane.showMessageDialog(null,"Bill has been Updated");
                 
            }else{
                
                String sqlInsert = "insert into Bill values('"+id+"','"+medCost+"','"+trtCost+"','"+totalCost+"')";
                Statement statementToShow2 = connection.createStatement();
                int row = statementToShow2.executeUpdate(sqlInsert);
                JOptionPane.showMessageDialog(null,"Bill has been Added");
            }
            
        }catch(Exception e)
        {
//            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        int selectedOption = JOptionPane.showConfirmDialog(null,
            "Do you wanna close the window?",
            "Choose",
            JOptionPane.YES_NO_OPTION);

        if (selectedOption == JOptionPane.YES_OPTION) {
            setVisible(false);
            new Add_recep().setVisible(true);

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment_recep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment_recep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment_recep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment_recep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment_recep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Mcosts;
    private javax.swing.JTextField MedicineCost;
    private javax.swing.JTextField Mname;
    private javax.swing.JTextField Quantity;
    private javax.swing.JTextField Totalc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel p_ID;
    private javax.swing.JTextField p_id;
    private javax.swing.JLabel t;
    private javax.swing.JTextField tCost;
    // End of variables declaration//GEN-END:variables
}
